version: "3.8"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    restart: always
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ADVERTISED_PORT: "9092" 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  walletdb:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=wallet
      - POSTGRES_PASSWORD=wallet
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - "./db:/db"
  debezium:
      image: debezium/connect:1.6
      ports:
        - "8083:8083"
      links:
        - kafka
        - walletdb
      environment:
        BOOTSTRAP_SERVERS: kafka:9092
        GROUP_ID: 1
        CONFIG_STORAGE_TOPIC: my_connect_configs
        OFFSET_STORAGE_TOPIC: my_connect_offsets
        STATUS_STORAGE_TOPIC: my_connect_statuses